### PR TITLE
Support alternative AWS account types

### LINKED ISSUE #28: Not compatible with alternative AWS account types, e.g. Gov Cloud
When using with roles in govcloud regions:

```Traceback (most recent call last):
  File "/usr/local/bin/aws-okta-processor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/aws_okta_processor/cli.py", line 74, in main
    command.run()
  File "/usr/local/lib/python3.8/site-packages/aws_okta_processor/commands/authenticate.py", line 76, in run
    credentials = self.authenticate()
  File "/usr/local/lib/python3.8/site-packages/aws_okta_processor/commands/authenticate.py", line 70, in authenticate
    credentials = saml_fetcher.fetch_credentials()
  File "/usr/local/lib/python3.8/site-packages/aws_okta_processor/core/fetcher.py", line 35, in fetch_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.8/site-packages/aws_okta_processor/core/fetcher.py", line 110, in _get_credentials
    response = client.assume_role_with_saml(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidIdentityTokenException: An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithSAML operation: Specified provider doesn't exist (Service: AWSOpenIdDiscoveryService; Status Code: 400; Error Code: AuthSamlManifestNotFoundException; Request ID: eecadabf-e743-4d91-951a-84d992dbb6ba; Proxy: null)```

The cause seems to be the boto3 default STS endpoint, which doesn't work with roles in other AWS partitions. The fix would be to provide the ability to optionally specify the boto3 client region.

### PR DESCRIPTION
**Pull request by woz5999**
Fixes #28 by adding an optional AWS region configuration

### CODE REVIEW

**Comment by woz5999** [comment]
@tahoward  what's the best way to get this reviewed and merged?

**Comment by woz5999** [comment]
@smccarthy @tahoward Our team would love to start using this tool, but due to our dual AWS setup, it's unusable for us without this support. Can you provide more guidance for what it will take to get this merged?

**Comment by tahoward** [comment]
Taking a look now!

**Comment by woz5999** [comment]
Thanks a lot guys. Have a great weekend.

**Pull request merged**
